from .vehicles.vehicle_details import vehicle_details
from .vehicles.vehicle_list import  vehicle_list
from .vehicles.vehicle_form import vehicle_form
from .vehicles.vehicle_form import vehicle_edit_form
from .connection import Connection
from .employees.employee_list import  employee_list
from .employees.employee_form import employee_form
from .employees.employee_form import employee_edit_form
from .employees.employee_details import employee_details
from .home import home
from .auth.logout import logout_user
from .departments.department_list import department_list
from .departments.department_form import department_form
from .departments.department_details import department_details
from .jobs.job_past import job_past
from .jobs.job_list import job_list
from .jobs.job_form import job_form
from .jobs.job_form import job_edit_form
from .jobs.job_details import job_details