# Generated by Django 3.0.9 on 2020-09-16 18:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coastalapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='department',
            name='department_budget',
        ),
    ]
