# Generated by Django 3.0.9 on 2020-09-22 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('coastalapp', '0004_job_assigned_employee'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='job',
            name='assigned_employee',
        ),
    ]
