# Generated by Django 3.0.9 on 2020-09-22 15:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coastalapp', '0005_remove_job_assigned_employee'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmployeeJob',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assigned_date', models.DateField(null=True)),
                ('unassigned_date', models.DateField(null=True)),
                ('employee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeeJobs', to='coastalapp.Employee')),
                ('job', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='EmployeesJob', to='coastalapp.Job')),
            ],
        ),
    ]
