# Generated by Django 3.0.9 on 2020-09-23 15:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('coastalapp', '0006_employeejob'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeejob',
            name='employee',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coastalapp.Employee'),
        ),
        migrations.AlterField(
            model_name='employeejob',
            name='job',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='coastalapp.Job'),
        ),
    ]
